version: "3.7"

services:
  # proxy:
  #   image: mijabr/mijabr-proxy:arm

  identity:
    image: mijabr/mijabr-identity:arm
    ports:
      - "80:80"
    env_file:
      - hosts-mijabr.env

  home:
    image: mijabr/mijabr-home:arm
    env_file:
      - hosts-mijabr.env
    
  scrabble:
    image: mijabr/mijabr-scrabble:arm
    env_file:
      - hosts-mijabr.env
  