version: "3.7"

services:
  # proxy:
  #   image: mijabr/mijabr-proxy:arm

  identity:
    image: mijabr/mijabr-identity:arm
    ports:
      - "80:80"

  home:
    image: mijabr/mijabr-home:arm
    
  scrabble:
    image: mijabr/mijabr-scrabble:arm
  